name: flutter_mcp_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  mcp_server: ^1.0.3
  yaml: ^3.1.0 #Needed for yaml manipulation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
